# -*- coding: utf-8 -*-
"""LAB3_ANOVA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2kRD6GBiWwVk7PDLLKqCNCuOSfVmAG_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(color_codes=True)
import statsmodels.api as sm
from statsmodels.formula.api import ols
from scipy import stats
from statsmodels.stats.multicomp import pairwise_tukeyhsd

df = pd.read_csv("WorldEnergy.csv")
df.head(15)

df = df.dropna()  # dropping null values
df.count()        # displaying latest data count after removing null values.

df.info()

print(df.isna().sum())

# Barplot
sns.barplot(x='country', y='greenhouse_gas_emissions', hue='country', data=df, \
            errorbar=None, palette='muted', legend=False )
plt.title('Greenhouse gas emissions (GHE) by countries')
plt.show()

#Partitioning the continuous data into 3 categories for ANOVA
df['fossil_level'] = pd.qcut(df['fossil_fuel_consumption'], q=3, labels=['Low', 'Medium', 'High'])
df['coal_level'] = pd.qcut(df['coal_consumption'], q=2, labels=['Low_C', 'High_C'])
df['gas_level'] = pd.qcut(df['gas_consumption'], q=2, labels=['Low_G', 'High_G'])

# One-Way ANOVA
model_1way = ols('greenhouse_gas_emissions ~ C(fossil_level)', data=df).fit()
anova_1way = sm.stats.anova_lm(model_1way, typ=2)
print(anova_1way)

# Interpretation
# If p-value < 0.05, reject null hypothesis
# F-statistic = ratio of between-group to within-group variation.

# Interpretation Logic
p_value_overall = model_1way.f_pvalue
if p_value_overall < 0.05:
    print(f"\nResult: Reject the Null Hypothesis (p-value: {p_value_overall:.4e})")
    print("Conclusion: NRE consumptions significantly contribute to greenhouse gas emissions.")
else:
    print(f"\nResult: Fail to Reject the Null Hypothesis (p-value: {p_value_overall:.4f})")
    print("Conclusion: There is no significant evidence that NRE consumptions affect GHG emissions.")

# Two-Way ANOVA (GHE ×  coal & gas level)
model_2way = ols('greenhouse_gas_emissions ~ C(coal_level) * C(gas_level)', data=df).fit()
anova_2way = sm.stats.anova_lm(model_2way, typ=2)
print(anova_2way)

# Interpretation
# coal_level: main effect of coal energy on GHE
# gas_level: main effect of gas level on GHE
#coal_level:gas_level -> interactiom effect

#Interpretation Logic
p_value_overall = model_2way.f_pvalue
if p_value_overall < 0.05:
    print(f"\nResult: Reject the Null Hypothesis (p-value: {p_value_overall:.4e})")

else:
    print(f"\nResult: Fail to Reject the Null Hypothesis (p-value: {p_value_overall:.4f})")

#Post-Hoc test
#Tukey's HSD for One-way ANOVA
#Comparing high, medium and low fossil fuel consumption
tukey_1way = pairwise_tukeyhsd(endog=df['greenhouse_gas_emissions'],
                              groups=df['fossil_level'],
                              alpha=0.05)

#Tukey's HSD for Two-way ANOVA
#to create a combined factor to compare all possible group combinations (e.g: high coal + low gas)
df['interaction_factor'] = df['coal_level'].astype(str) + "_" + df['gas_level'].astype(str)
tukey_2way = pairwise_tukeyhsd(endog=df['greenhouse_gas_emissions'],
                              groups=df['interaction_factor'],
                              alpha=0.05)

print("--- Tukey HSD One-way Results ---")
print(tukey_1way)
print("\n--- Tukey HSD Two-way Results ---")
print(tukey_2way)

#Levene's test: one-way ANOVA groups
#used to test for homogeneity of variances
f_low = df[df['fossil_level'] == 'Low']['greenhouse_gas_emissions']
f_med = df[df['fossil_level'] == 'Medium']['greenhouse_gas_emissions']
f_high = df[df['fossil_level'] == 'High']['greenhouse_gas_emissions']

levene_1way = stats.levene(f_low, f_med, f_high)

#Levene's Test for Two-way ANOVA groups (all combinations of coal and gas consumptions)
twoway_groups = [
    df[(df['coal_level'] == c) & (df['gas_level'] == g)]['greenhouse_gas_emissions']
    for c in ['Low', 'High'] for g in ['Low', 'High']
]
levene_2way = stats.levene(*twoway_groups)

print("--- Levene's Test Results ---")
print(f"One-way Groups: Statistic={levene_1way.statistic:.4f}, p-value={levene_1way.pvalue:.4e}")
print(f"Two-way Groups: Statistic={levene_2way.statistic:.4f}, p-value={levene_2way.pvalue:.4e}")

#Shapiro-Wilk test (Normality test)
#Testing the residuals of the models
shapiro_1way = stats.shapiro(model_1way.resid)
shapiro_2way = stats.shapiro(model_2way.resid)

print("--- Shapiro-Wilk Test Results (Normality of Residuals) ---")
print(f"One-way ANOVA: W={shapiro_1way.statistic:.4f}, p-value={shapiro_1way.pvalue:.4e}")
print(f"Two-way ANOVA: W={shapiro_2way.statistic:.4f}, p-value={shapiro_2way.pvalue:.4e}")

#Generate boxplot
plt.figure(figsize=(10, 6))
sns.boxplot(x='fossil_level', y='greenhouse_gas_emissions', data=df,
            order=['Low', 'Medium', 'High'], palette='Set2')
plt.title('Distribution of Greenhouse Gas Emissions by Fossil Fuel Consumption Level')
plt.xlabel('Fossil Fuel Consumption Level')
plt.ylabel('Greenhouse Gas Emissions (GHE)')
plt.grid(axis='y', linestyle='--', alpha=0.7)

#Interaction Plot
#If lines are not parallel → interaction effect exists.

sns.pointplot(x='gas_level', y='greenhouse_gas_emissions', hue='coal_level', data=df,
             errorbar='sd', dodge=True, markers=['o', 's'], capsize=.1)
plt.title('Interaction between coal energy and gas consumption')
plt.ylabel('GHE')
plt.show()

